---
category: agent-workflows
priority: medium
agents: [plan-agent]
description: "Documentation template management"
tags: [documentation, templates, adr, specs]
last_updated: "2025-09-07"
mcp_dependencies: []
---

# Documentation Templates Hook
# Defines and manages templates for different types of documentation

hook_name: documentation-templates
version: "1.0"
trigger: "on_documentation_creation"

# CORE DOCUMENTATION TEMPLATE ACTIONS
actions:
  use_adr_template:
    description: "Use a template for Architecture Decision Records (ADRs)"
    required: false
    implementation: |
      - An ADR should have a clear title, status, context, decision, and consequences
      - This ensures that architectural decisions are well-documented and easy to understand

  use_spec_template:
    description: "Use a template for technical specifications"
    required: false
    implementation: |
      - A technical spec should include sections for the problem statement, goals, non-goals, proposed solution, and alternatives considered
      - This provides a comprehensive overview of the technical design

  use_api_contract_template:
    description: "Use a template for API contracts"
    required: false
    implementation: |
      - An API contract should define the endpoints, methods, parameters, and responses for an API
      - This serves as a source of truth for both the API provider and consumer