---
category: agent-workflows
priority: medium
agents: [plan-agent]
description: "Requirements processing and validation"
tags: [requirements, analysis, validation, gaps]
last_updated: "2025-09-07"
mcp_dependencies: [sequentialthinking]
---

# Requirements Analysis Hook
# Defines a process for processing and validating project requirements

hook_name: requirements-analysis
version: "1.0"
trigger: "on_requirements_gathering"

# CORE REQUIREMENTS ANALYSIS ACTIONS
actions:
  analyze_functional_requirements:
    description: "Analyze the functional requirements of the project"
    required: true
    mcp_server: "sequentialthinking"
    implementation: |
      - Decompose high-level requirements into smaller, more detailed user stories
      - Define the acceptance criteria for each user story
      - Ensure that the functional requirements are clear, testable, and unambiguous

  analyze_non_functional_requirements:
    description: "Analyze the non-functional requirements of the project"
    required: true
    implementation: |
      - Identify requirements related to performance, security, reliability, and other non-functional aspects
      - Define measurable goals for each non-functional requirement
      - Ensure that the non-functional requirements are realistic and achievable

  identify_gaps_and_ambiguities:
    description: "Identify any gaps or ambiguities in the requirements"
    required: true
    implementation: |
      - Review the requirements for completeness and consistency
      - Ask clarifying questions to resolve any ambiguities
      - Document any assumptions that are made