---
category: mcp-integration
priority: medium
agents: [plan-agent, debug-agent, maker-agent]
description: "Complex reasoning through Sequential Thinking MCP"
tags: [sequentialthinking, mcp, reasoning, complex-problems, planning]
last_updated: "2025-09-07"
mcp_dependencies: [sequentialthinking]
---

# Sequential Thinking Hook
# Enables complex reasoning and problem decomposition through the Sequential Thinking MCP

hook_name: sequential-thinking
version: "1.0"
trigger: "on_complex_problem"

# CORE SEQUENTIAL THINKING ACTIONS
actions:
  decompose_problem:
    description: "Break down complex problems into smaller, manageable steps"
    required: true
    mcp_server: "sequentialthinking"
    implementation: |
      - Analyze the problem statement and identify key components
      - Create a step-by-step plan for solving the problem
      - Define the inputs and outputs for each step
      - Ensure that the plan is logical and covers all aspects of the problem
    fallback: "use native reasoning capabilities"

  analyze_tradeoffs:
    description: "Systematically analyze the trade-offs of different solutions"
    required: false
    mcp_server: "sequentialthinking"
    implementation: |
      - Identify the possible solutions to the problem
      - Define the criteria for evaluating the solutions
      - Analyze the pros and cons of each solution
      - Provide a recommendation based on the analysis
    fallback: "use native reasoning capabilities"

  develop_strategy:
    description: "Develop a comprehensive strategy for implementing a solution"
    required: false
    mcp_server: "sequentialthinking"
    implementation: |
      - Define the overall goals and objectives
      - Create a roadmap with milestones and deliverables
      - Identify the resources and dependencies required
      - Define the metrics for measuring success
    fallback: "use native reasoning capabilities"