---
category: agent-workflows
priority: high
agents: [debug-agent]
description: "Log file investigation and analysis"
tags: [log-analysis, parsing, correlation, timeline]
last_updated: "2025-09-07"
mcp_dependencies: [filesystem]
---

# Log Analysis Hook
# Defines a process for investigating and analyzing log files

hook_name: log-analysis
version: "1.0"
trigger: "on_log_file_read"

# CORE LOG ANALYSIS ACTIONS
actions:
  parse_log_entries:
    description: "Parse structured and unstructured log entries"
    required: true
    mcp_server: "filesystem"
    implementation: |
      - Use regular expressions to parse unstructured log entries
      - For structured logs (e.g., JSON), parse the content and extract key fields
      - Handle different log formats from different services

  correlate_log_entries:
    description: "Correlate log entries across different services"
    required: true
    implementation: |
      - Use a correlation ID to trace a single request across multiple services
      - Build a timeline of events to understand the sequence of operations

  filter_and_search_logs:
    description: "Filter and search logs to find relevant information"
    required: true
    mcp_server: "filesystem"
    implementation: |
      - Filter logs by time, log level, service, or other criteria
      - Use full-text search to find specific error messages or keywords