---
category: agent-workflows
priority: high
agents: [debug-agent]
description: "Root cause analysis frameworks and templates"
tags: [root-cause, analysis, five-whys, fishbone]
last_updated: "2025-09-07"
mcp_dependencies: [sequentialthinking]
---

# Root Cause Analysis Hook
# Defines frameworks and templates for performing root cause analysis

hook_name: root-cause-analysis
version: "1.0"
trigger: "on_failure_analysis"

# CORE ROOT CAUSE ANALYSIS ACTIONS
actions:
  apply_five_whys:
    description: "Apply the Five Whys technique to identify the root cause of a problem"
    required: true
    mcp_server: "sequentialthinking"
    implementation: |
      - Start with the problem and ask "Why?" five times
      - Each answer forms the basis of the next question
      - The goal is to get to the root cause of the problem, not just the symptoms

  use_fishbone_diagram:
    description: "Use a fishbone diagram (Ishikawa diagram) to brainstorm potential causes of a problem"
    required: false
    implementation: |
      - Create a diagram with the problem at the head of the fish
      - Brainstorm potential causes and group them into categories (e.g., people, process, technology)
      - This helps to identify a wide range of potential causes

  perform_fault_tree_analysis:
    description: "Perform a fault tree analysis to identify the root causes of a system failure"
    required: false
    implementation: |
      - Start with the top-level failure and work backwards to identify all the potential causes
      - Use boolean logic to represent the relationships between the causes
      - This is a more formal and quantitative approach to root cause analysis