---
category: agent-workflows
priority: medium
agents: [debug-agent]
description: "System-level debugging and diagnostics"
tags: [system-diagnostics, resources, processes, network]
last_updated: "2025-09-07"
mcp_dependencies: []
---

# System Diagnostics Hook
# Defines a process for performing system-level debugging and diagnostics

hook_name: system-diagnostics
version: "1.0"
trigger: "on_system_error"

# CORE SYSTEM DIAGNOSTICS ACTIONS
actions:
  check_resource_utilization:
    description: "Check the utilization of system resources"
    required: true
    implementation: |
      - Use tools like `top`, `htop`, or `ps` to check CPU and memory utilization
      - Use `df` to check disk space utilization
      - Look for any resource constraints that may be causing the issue

  inspect_running_processes:
    description: "Inspect the running processes on the system"
    required: true
    implementation: |
      - Use `ps` or `pgrep` to find the process ID of the application
      - Use `lsof` to see what files and network connections the process has open
      - Use `strace` or `dtruss` to trace the system calls that the process is making

  analyze_network_traffic:
    description: "Analyze the network traffic to and from the application"
    required: false
    implementation: |
      - Use `tcpdump` or `wireshark` to capture network traffic
      - Look for any network errors or unexpected traffic patterns
      - Check for firewall rules that may be blocking traffic