---
category: agent-workflows
priority: medium
agents: [docs-agent]
description: "API documentation generation"
tags: [api-docs, endpoints, parameters, examples]
last_updated: "2025-09-07"
mcp_dependencies: [context7]
---

# API Documentation Hook
# Defines a process for generating API documentation

hook_name: api-documentation
version: "1.0"
trigger: "on_api_change"

# CORE API DOCUMENTATION ACTIONS
actions:
  document_endpoints:
    description: "Document all the endpoints of the API"
    required: true
    implementation: |
      - For each endpoint, document the URL, HTTP method, and a brief description
      - Use a consistent format for all endpoint documentation

  document_parameters:
    description: "Document the parameters for each endpoint"
    required: true
    implementation: |
      - For each parameter, document its name, type, and whether it is required
      - Provide a clear description of what the parameter is used for

  document_responses:
    description: "Document the possible responses for each endpoint"
    required: true
    implementation: |
      - For each response, document the HTTP status code and a description of what it means
      - Provide an example of the response body

  add_code_examples:
    description: "Add code examples to demonstrate how to use the API"
    required: true
    mcp_server: "context7"
    implementation: |
      - Provide code examples in multiple languages (e.g., cURL, Python, JavaScript)
      - Use the context7 MCP to get official library examples where possible