---
category: agent-workflows
priority: medium
agents: [docs-agent]
description: "Code documentation standards and generation"
tags: [code-comments, documentation, jsdoc, docstrings]
last_updated: "2025-09-07"
mcp_dependencies: []
---

# Code Comments Hook
# Defines standards for writing and generating code comments

hook_name: code-comments
version: "1.0"
trigger: "on_code_write"

# CORE CODE COMMENT ACTIONS
actions:
  add_function_docstrings:
    description: "Add docstrings to all public functions and methods"
    required: true
    implementation: |
      - The docstring should include a brief description of what the function does
      - It should also document the parameters,
      - return value, and any exceptions that may be thrown

  add_inline_comments:
    description: "Add inline comments to explain complex or non-obvious code"
    required: false
    implementation: |
      - Use inline comments to explain the "why" behind the code, not just the "what"
      - Keep the comments concise and to the point

  use_comment_tags:
    description: "Use special comment tags to highlight important information"
    required: false
    implementation: |
      - Use `TODO` to mark areas of the code that need to be completed
      - Use `FIXME` to mark areas of the code that need to be fixed
      - Use `HACK` to mark temporary or suboptimal solutions