---
category: agent-workflows
priority: medium
agents: [docs-agent]
description: "Documentation quality assurance"
tags: [documentation-quality, validation, links, examples]
last_updated: "2025-09-07"
mcp_dependencies: [context7]
---

# Documentation Quality Hook
# Defines a process for ensuring the quality of the documentation

hook_name: documentation-quality
version: "1.0"
trigger: "on_documentation_write"

# CORE DOCUMENTATION QUALITY ACTIONS
actions:
  check_for_completeness:
    description: "Check that the documentation is complete and covers all aspects of the feature"
    required: true
    implementation: |
      - Ensure that all public functions and methods are documented
      - Check that all parameters and return values are documented
      - Verify that all error conditions are documented

  validate_accuracy:
    description: "Validate that the documentation is accurate and up to date"
    required: true
    mcp_server: "context7"
    implementation: |
      - Check that the code examples are correct and work as expected
      - Use the context7 MCP to verify that the documentation matches the latest version of the library
      - Manually review the documentation for any inaccuracies

  ensure_consistency:
    description: "Ensure that the documentation is consistent in style and tone"
    required: true
    implementation: |
      - Use a style guide to ensure consistent terminology and formatting
      - Run a linter to check for grammar and spelling errors

  validate_links:
    description: "Validate that all links in the documentation are working"
    required: false
    implementation: |
      - Use a link checker to find any broken links
      - Check both internal and external links