---
category: agent-workflows
priority: medium
agents: [docs-agent]
description: "Documentation category management"
tags: [documentation, types, categories, templates]
last_updated: "2025-09-07"
mcp_dependencies: [filesystem]
---

# Documentation Types Hook
# Defines and manages different categories of documentation

hook_name: documentation-types
version: "1.0"
trigger: "on_documentation_creation"

# CORE DOCUMENTATION TYPE ACTIONS
actions:
  create_user_documentation:
    description: "Create documentation for end-users"
    required: false
    implementation: |
      - Write getting started guides, tutorials, and how-to guides
      - Create a FAQ to answer common questions
      - Provide troubleshooting guides for common issues

  create_developer_documentation:
    description: "Create documentation for developers"
    required: false
    implementation: |
      - Write API reference documentation
      - Create code examples and tutorials
      - Document the architecture and design of the system

  create_operations_documentation:
    description: "Create documentation for operations teams"
    required: false
    implementation: |
      - Write deployment guides and configuration references
      - Document monitoring and backup procedures
      - Create a disaster recovery plan