---
category: agent-workflows
priority: low
agents: [docs-agent]
description: "Markdown formatting standards"
tags: [markdown, formatting, standards, best-practices]
last_updated: "2025-09-07"
mcp_dependencies: []
---

# Markdown Best Practices Hook
# Defines and enforces best practices for writing Markdown

hook_name: markdown-best-practices
version: "1.0"
trigger: "on_documentation_write"

# CORE MARKDOWN BEST PRACTICES ACTIONS
actions:
  use_proper_heading_hierarchy:
    description: "Use a proper heading hierarchy to structure the document"
    required: true
    implementation: |
      - Use a single H1 heading for the document title
      - Use H2 headings for major sections, H3 for subsections, and so on
      - Do not skip heading levels

  format_code_blocks:
    description: "Format code blocks for readability"
    required: true
    implementation: |
      - Use fenced code blocks with syntax highlighting
      - Specify the language of the code block to enable syntax highlighting
      - Use consistent indentation and formatting for the code

  use_semantic_line_breaks:
    description: "Use semantic line breaks to make the Markdown source easier to read and diff"
    required: false
    implementation: |
      - Break long lines at natural stopping points, such as the end of a sentence
      - This makes it easier to review changes and identify what has changed

  create_tables_for_tabular_data:
    description: "Use tables to present tabular data"
    required: false
    implementation: |
      - Use Markdown tables to present data in a structured way
      - Ensure that the columns are properly aligned for readability