---
category: quality
priority: medium
agents: [test-agent]
description: "Code coverage requirements and analysis"
tags: [code-coverage, metrics, gaps, reporting]
last_updated: "2025-09-07"
mcp_dependencies: [serena, filesystem]
---

# Coverage Standards Hook
# Defines and enforces code coverage standards

hook_name: coverage-standards
version: "1.0"
trigger: "after_test_execution"

# CORE COVERAGE ACTIONS
actions:
  measure_coverage:
    description: "Measure code coverage and generate a report"
    required: true
    mcp_server: "filesystem"
    implementation: |
      - Use a code coverage tool (e.g., Istanbul, LCOV) to collect coverage data
      - Generate an HTML report that visualizes the coverage of each file and line
      - Output a summary of the coverage metrics to the console

  enforce_coverage_thresholds:
    description: "Enforce minimum code coverage thresholds"
    required: true
    implementation: |
      - Define coverage thresholds for lines, branches, and functions
      - Fail the quality gate if the coverage is below the defined thresholds
      - Provide a clear error message indicating which thresholds were not met

  identify_coverage_gaps:
    description: "Identify areas of the code that are not covered by tests"
    required: false
    mcp_server: "serena"
    implementation: |
      - Analyze the coverage report to find uncovered files, functions, and branches
      - Use semantic analysis to identify critical areas of the code that lack coverage
      - Suggest new test cases to improve coverage in these areas