---
category: quality
priority: high
agents: [security-agent]
description: "Dependency vulnerability and compliance scanning"
tags: [dependencies, vulnerabilities, licenses, supply-chain]
last_updated: "2025-09-07"
mcp_dependencies: [filesystem]
---

# Dependency Scanning Hook
# Defines a process for scanning dependencies for vulnerabilities and compliance issues

hook_name: dependency-scanning
version: "1.0"
trigger: "on_dependency_change"

# CORE DEPENDENCY SCANNING ACTIONS
actions:
  scan_for_vulnerabilities:
    description: "Scan dependencies for known vulnerabilities"
    required: true
    mcp_server: "filesystem"
    implementation: |
      - Use a tool like npm audit, yarn audit, or safety to scan for vulnerabilities
      - Fail the quality gate if any high or critical vulnerabilities are found
      - Provide recommendations for upgrading or patching vulnerable dependencies

  check_license_compliance:
    description: "Check the licenses of all dependencies for compliance"
    required: false
    implementation: |
      - Use a tool like license-checker to identify the licenses of all dependencies
      - Compare the licenses against a whitelist of approved licenses
      - Flag any dependencies with non-compliant licenses

  identify_outdated_dependencies:
    description: "Identify dependencies that are out of date"
    required: false
    implementation: |
      - Use a tool like npm outdated or pip-review to find outdated dependencies
      - Encourage developers to keep dependencies up to date to receive security patches