---
category: quality
priority: high
agents: [security-agent]
description: "OWASP Top 10 vulnerability assessment"
tags: [owasp, security, top10, vulnerabilities, assessment]
last_updated: "2025-09-07"
mcp_dependencies: [serena]
---

# OWASP Top 10 Hook
# Defines checks for the OWASP Top 10 web application security risks

hook_name: owasp-top10
version: "1.0"
trigger: "on_security_scan"

# CORE OWASP TOP 10 CHECKS
actions:
  check_broken_access_control:
    description: "Check for broken access control vulnerabilities"
    required: true
    implementation: |
      - Ensure that all sensitive operations require authentication and authorization
      - Check for insecure direct object references (IDOR)
      - Validate that users can only access their own data

  check_cryptographic_failures:
    description: "Check for cryptographic failures"
    required: true
    implementation: |
      - Ensure that sensitive data is encrypted at rest and in transit
      - Check for the use of weak or outdated cryptographic algorithms
      - Validate that keys are managed securely

  check_injection_flaws:
    description: "Check for injection flaws"
    required: true
    mcp_server: "serena"
    implementation: |
      - Scan for SQL, NoSQL, and command injection vulnerabilities
      - Ensure that all user input is properly validated and sanitized
      - Use parameterized queries to prevent SQL injection

  check_insecure_design:
    description: "Check for insecure design patterns"
    required: false
    implementation: |
      - Review the application architecture for security flaws
      - Look for missing or ineffective security controls
      - Ensure that security is considered throughout the development lifecycle

  check_security_misconfiguration:
    description: "Check for security misconfigurations"
    required: true
    implementation: |
      - Review the configuration of servers, frameworks, and libraries
      - Check for default credentials, open ports, and other common misconfigurations
      - Ensure that security headers are properly configured