---
category: quality
priority: high
agents: [security-agent]
description: "Detection of exposed secrets and credentials"
tags: [secrets, credentials, api-keys, tokens, entropy]
last_updated: "2025-09-07"
mcp_dependencies: [filesystem]
---

# Secrets Detection Hook
# Defines a process for detecting exposed secrets and credentials in the codebase

hook_name: secrets-detection
version: "1.0"
trigger: "on_code_write"

# CORE SECRETS DETECTION ACTIONS
actions:
  scan_for_secrets:
    description: "Scan files for patterns that match common secret formats"
    required: true
    mcp_server: "filesystem"
    implementation: |
      - Use a tool like truffleHog or gitleaks to scan for secrets
      - Check for high-entropy strings that may be keys or tokens
      - Look for common keywords like "API_KEY", "PASSWORD", or "SECRET"

  validate_false_positives:
    description: "Validate potential secrets to reduce false positives"
    required: true
    implementation: |
      - For well-known APIs (e.g., AWS, Stripe), try to validate the format of the key
      - Check the context of the potential secret to see if it is used in a sensitive way
      - Cross-reference with a list of known false positives

  report_findings:
    description: "Report any found secrets to the appropriate channels"
    required: true
    implementation: |
      - Fail the quality gate if any secrets are found
      - Create a high-priority issue in the issue tracker
      - Notify the security team immediately