---
category: quality
priority: high
agents: [security-agent]
description: "Secure coding practices and standards"
tags: [secure-coding, validation, encoding, parameterized-queries]
last_updated: "2025-09-07"
mcp_dependencies: []
---

# Secure Coding Hook
# Defines and enforces secure coding practices

hook_name: secure-coding
version: "1.0"
trigger: "on_code_write"

# CORE SECURE CODING ACTIONS
actions:
  enforce_input_validation:
    description: "Ensure that all user input is validated and sanitized"
    required: true
    implementation: |
      - Use a whitelist approach to validate input
      - Check for expected data types, lengths, and formats
      - Sanitize input to prevent injection attacks

  enforce_output_encoding:
    description: "Ensure that all output is properly encoded to prevent XSS"
    required: true
    implementation: |
      - Use context-aware output encoding
      - HTML-encode output that is rendered in a browser
      - Use a library or framework that provides automatic output encoding

  use_parameterized_queries:
    description: "Enforce the use of parameterized queries to prevent SQL injection"
    required: true
    implementation: |
      - Use prepared statements or parameterized queries for all database access
      - Avoid building SQL queries with string concatenation

  manage_secrets_securely:
    description: "Ensure that secrets are not hard-coded in the source code"
    required: true
    implementation: |
      - Store secrets in a secure vault or environment variables
      - Do not log secrets or other sensitive information
      - Rotate secrets regularly