---
category: quality
priority: medium
agents: [test-agent]
description: "Testing best practices and patterns"
tags: [test-patterns, best-practices, aaa, bdd]
last_updated: "2025-09-07"
mcp_dependencies: []
---

# Test Patterns Hook
# Defines and enforces best practices for writing tests

hook_name: test-patterns
version: "1.0"
trigger: "on_test_write"

# CORE TEST PATTERN ACTIONS
actions:
  enforce_aaa_pattern:
    description: "Enforce the Arrange-Act-Assert (AAA) pattern for unit tests"
    required: true
    implementation: |
      - Ensure that each test has a clear Arrange, Act, and Assert section
      - The Arrange section should set up the test environment and inputs
      - The Act section should call the code being tested
      - The Assert section should check that the output is as expected

  promote_bdd_style:
    description: "Promote the use of Behavior-Driven Development (BDD) style for acceptance tests"
    required: false
    implementation: |
      - Encourage the use of Gherkin syntax (Given-When-Then) to describe test scenarios
      - This makes the tests more readable and understandable for non-technical stakeholders

  use_test_data_builders:
    description: "Promote the use of the Test Data Builder pattern for creating test data"
    required: false
    implementation: |
      - Instead of creating test data inline, use a builder function or class
      - This makes the tests cleaner and easier to maintain, especially for complex data structures

  manage_mocks_and_stubs:
    description: "Define a consistent strategy for using mocks and stubs"
    required: true
    implementation: |
      - Use mocks to isolate the code being tested from its dependencies
      - Avoid overusing mocks, which can make the tests brittle
      - Use a mocking framework (e.g., Sinon.js, Mockito) to simplify the creation of mocks