---
category: quality
priority: high
agents: [test-agent]
description: "Management of different test categories and execution"
tags: [unit-tests, integration-tests, e2e-tests, performance-tests]
last_updated: "2025-09-07"
mcp_dependencies: [filesystem]
---

# Test Types Hook
# Defines and manages different categories of tests

hook_name: test-types
version: "1.0"
trigger: "on_test_execution"

# CORE TEST TYPE ACTIONS
actions:
  run_unit_tests:
    description: "Run fast, isolated unit tests"
    required: true
    mcp_server: "filesystem"
    implementation: |
      - Discover all files matching the unit test pattern (e.g., *.test.js)
      - Run the tests using the appropriate test runner (e.g., Jest, Pytest)
      - Ensure that tests are run in parallel for maximum efficiency

  run_integration_tests:
    description: "Run tests that verify the interaction between components"
    required: true
    mcp_server: "filesystem"
    implementation: |
      - Set up the necessary infrastructure (e.g., databases, message queues)
      - Run tests that cover the interaction points between services
      - Tear down the infrastructure after the tests are complete

  run_e2e_tests:
    description: "Run end-to-end tests that simulate user workflows"
    required: false
    mcp_server: "filesystem"
    implementation: |
      - Use a browser automation framework (e.g., Playwright, Cypress)
      - Simulate user interactions with the application's UI
      - Validate that the application behaves as expected from the user's perspective

  run_performance_tests:
    description: "Run tests to measure the performance and scalability of the system"
    required: false
    implementation: |
      - Use a load testing tool (e.g., k6, JMeter)
      - Measure metrics such as response time, throughput, and resource utilization
      - Compare the results against performance targets