---
category: quality
priority: high
agents: [security-agent]
description: "Common vulnerability pattern detection"
tags: [security, vulnerabilities, sql-injection, xss, csrf]
last_updated: "2025-09-07"
mcp_dependencies: [serena]
---

# Vulnerability Patterns Hook
# Defines patterns for detecting common security vulnerabilities

hook_name: vulnerability-patterns
version: "1.0"
trigger: "on_security_scan"

# CORE VULNERABILITY PATTERN ACTIONS
actions:
  detect_sql_injection:
    description: "Detect potential SQL injection vulnerabilities"
    required: true
    mcp_server: "serena"
    implementation: |
      - Trace data flow from user input to database queries
      - Look for string concatenation in SQL queries
      - Flag any use of non-parameterized queries

  detect_xss:
    description: "Detect potential Cross-Site Scripting (XSS) vulnerabilities"
    required: true
    mcp_server: "serena"
    implementation: |
      - Trace data flow from user input to HTML output
      - Look for cases where user input is rendered without proper escaping
      - Flag any use of dangerous HTML rendering functions (e.g., innerHTML)

  detect_csrf:
    description: "Detect potential Cross-Site Request Forgery (CSRF) vulnerabilities"
    required: false
    implementation: |
      - Check that all state-changing requests use a CSRF token
      - Ensure that the SameSite attribute is set on session cookies

  detect_command_injection:
    description: "Detect potential command injection vulnerabilities"
    required: true
    mcp_server: "serena"
    implementation: |
      - Trace data flow from user input to system commands
      - Flag any use of user input in shell commands without proper sanitization